version: '3.8'

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: personal-finance-prod
    environment:
      - NODE_ENV=production
    command: bash
